version: "3"
services:
  rmd:
    image: joelnitta/nectandra_ferns:3.6.1
    volumes:
      - ".:/home/rstudio/nectandra"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/nectandra
