version: "3"
services:
  analysis:
    image: joelnitta/nectandra_ferns:3.6.1
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/nectandra"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/nectandra
