# Load packages
library(jntools)
library(taxastand)
library(drake)
library(here)
library(readxl)
library(iNEXT)
library(assertr)
library(ips)
library(broom)
library(ggridges)
library(magick)
library(patchwork)
library(janitor)
library(raster)
library(ggtree)
library(ggrepel)
library(cowplot)
library(scico)
library(scales)
library(tidyverse)
library(conflicted)

# Resolve conflicts
conflict_prefer("Position", "ggplot2")
conflict_prefer("collapse", "dplyr")
conflict_prefer("expand", "tidyr")
conflict_prefer("extract", "magrittr")
conflict_prefer("filter", "dplyr")
conflict_prefer("flatten", "purrr")
conflict_prefer("gather", "tidyr")
conflict_prefer("here", "here")
conflict_prefer("intersect", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("map", "purrr")
conflict_prefer("select", "dplyr")
conflict_prefer("setdiff", "dplyr")
conflict_prefer("union", "dplyr")